### PR TITLE
add getData to kqueue,epoll

### PR DESCRIPTION
**Pull request by bung87**
just port from nim std

### CODE REVIEW

**Comment by cheatfate** [comment]
I understand that you trying to make it compatible with std, but i don't see any reasons why this calls should be present.

**Comment by bung87** [comment]
https://github.com/bung87/httpbeast/tree/chronos Am trying to replace httpbeast asyncdispatch when verified will port this part to my web framework

**Comment by cheatfate** [comment]
I'm going to reject this PR because of following reasons:
1. Solution provided is not cross-platform, e.g. Windows support is not provided.
2. There no actual reasons for `chronos` was presented.

**Comment by bung87** [comment]
I agree with 2. only need selectors when no `async` used,  I dont understand 1. `getData` already in `ioselectors_select.nim `

**Pull request closed without merging**
