### PR TITLE
Enable --gc:orc testing for nim-chronos

### PR DESCRIPTION
**Pull request by Araq**
Don't forget to "squash" my commits.

### CODE REVIEW

**Comment by sinkingsugar** [comment]
Tests are green, maybe this can be closed as well https://github.com/status-im/nim-chronos/pull/135

**Comment by sinkingsugar** [comment]
Curious about perf btw, some many months ago orc builds were quite a perf hit on reference heavy code due to cycles.
Of course the way I wrote that code was with the GC in mind so the blame is not really on the ORC.
Yet it's a paradigm shift, old codebases might need big refactoring.
Chronos uses lot of cycling references afaik.

**Comment by Araq** [comment]
In my experience raw throughput is worse (by about 20%) but latency is better by orders of magnitude because there is no "stop the world" phase and WCET can be measured effectively (it's very predictable). Memory consumption can be reduced by a factor of 2. You can also tweak Orc with the new annotations in ways that were previously impossible -- I never look back once a project works with Orc.

**Comment by sinkingsugar** [comment]
> In my experience raw throughput is worse (by about 20%) but latency is better by orders of magnitude because there is no "stop the world" phase and WCET can be measured effectively (it's very predictable). Memory consumption can be reduced by a factor of 2. You can also tweak Orc with the new annotations in ways that were previously impossible -- I never look back once a project works with Orc.

Yeah, that's for sure.
But my point is that the old GC tricked us into very bad coding habits often, way too many refs and cycles. With ORC and most of all destructors/constructors value types are to be preferred when possible.

**Review by arnetheduck — APPROVED** [review]

**Pull request merged**
