### PR TITLE
[WIP] Zero-cost unattended Future[T] tracking mechanism.

### PR DESCRIPTION
**Pull request by cheatfate**
Implementation of https://github.com/status-im/nim-chronos/issues/31 and https://github.com/status-im/nim-beacon-chain/issues/1121

### CODE REVIEW

**Comment by stefantalpalaru** [comment]
> zero-cost

You now have to maintain a linked list on top of everything else already in there...

> tracking mechanism

Why do you have two different mechanisms for counting pending futures? Which one don't you trust?

**Comment by stefantalpalaru** [comment]
> Add documentation for dump procedure.

That's just a comment. Documentation should go in a README.

**Comment by cheatfate** [comment]
Its zero-cost in terms of performance, because add/remove operation from linked-list is O(1) operation.

**Comment by stefantalpalaru** [comment]
> add/remove operation from linked-list is O(1) operation

How about traversing it to count the items?

**Comment by cheatfate** [comment]
There no need to traverse all the list to count number of items because counter is maintained here https://github.com/status-im/nim-chronos/pull/106/files#diff-f40be194bab41c19482e724c50a7172bR68 . This procedure https://github.com/status-im/nim-chronos/pull/106/files#diff-1bf11876eadbeac0818889c899d51e56R14 is only used in tests to confirm that counter is working properly.

**Comment by stefantalpalaru** [comment]
OK

**Comment by cheatfate** [comment]
I have made benchmarks of this solution on Windows, using this sample program:
```nim
import chronos

proc createServer(address: TransportAddress): Future[StreamServer] {.async.} =
  proc serve(server: StreamServer, transp: StreamTransport) {.async.} =
    let expect = "REQUEST"
    var buffer = newSeq[byte](len(expect))
    try:
      await transp.readExactly(addr buffer[0], len(buffer))
      discard await transp.write("ANSWER")
    finally:
      await transp.closeWait()

  var server = createStreamServer(address, serve, {ReuseAddr})
  server.start()
  return server

proc client(address: TransportAddress) {.async.} =
  let expect = "ANSWER"
  var buffer = newSeq[byte](len(expect))
  for i in 0 ..< 100_000:
    if i mod 10_000 == 0:
      echo i
    let transp = await connect(address)
    try:
      discard await transp.write("REQUEST")
      await transp.readExactly(addr buffer[0], len(buffer))
    finally:
      await transp.closeWait()

proc test(): Future[Duration] {.async.} =
  let address = initTAddress("127.0.0.1:34567")
  let sm = Moment.now()
  let server = await createServer(address)
  await client(address)
  server.stop()
  await server.closeWait()
  let em = Moment.now()
  result = (em - sm)

when isMainModule:
  echo waitFor(test())
  echo GC_getStatistics()
  echo dumpPendingFutures()
```

#### Benchmark for chronos with Future[T] tracking mechanism:

```
cheatfate@DESKTOP MINGW64 /c/Projects
$  [Nimbus env]$ ./benchchronos.exe
0
10000
20000
30000
40000
50000
60000
70000
80000
90000
20s977ms835us800ns
[GC] total memory: 4886528
[GC] occupied memory: 823840
[GC] stack scans: 2347
[GC] stack cells: 59
[GC] cycle collections: 568
[GC] max threshold: 4194304
[GC] zct capacity: 1024
[GC] max cycle table size: 0
[GC] max pause time [ms]: 0
[GC] max stack size: 2288

1 pending Future[T] objects found:
Future[0] with name "test" created at <asyncmacro2.nim:193> and state = Finished


cheatfate@DESKTOP MINGW64 /c/Projects
$  [Nimbus env]$ ./benchchronos.exe
0
10000
20000
30000
40000
50000
60000
70000
80000
90000
20s985ms185us500ns
[GC] total memory: 4886528
[GC] occupied memory: 857632
[GC] stack scans: 2372
[GC] stack cells: 59
[GC] cycle collections: 568
[GC] max threshold: 4194304
[GC] zct capacity: 1024
[GC] max cycle table size: 0
[GC] max pause time [ms]: 0
[GC] max stack size: 2288

1 pending Future[T] objects found:
Future[0] with name "test" created at <asyncmacro2.nim:193> and state = Finished

cheatfate@DESKTOP MINGW64 /c/Projects
$  [Nimbus env]$ ./benchchronos.exe
0
10000
20000
30000
40000
50000
60000
70000
80000
90000
21s88ms639us700ns
[GC] total memory: 4886528
[GC] occupied memory: 871128
[GC] stack scans: 2362
[GC] stack cells: 59
[GC] cycle collections: 568
[GC] max threshold: 4194304
[GC] zct capacity: 1024
[GC] max cycle table size: 0
[GC] max pause time [ms]: 0
[GC] max stack size: 2288

1 pending Future[T] objects found:
Future[0] with name "test" created at <asyncmacro2.nim:193> and state = Finished
```

#### Benchmark for chronos without Future[T] tracking mechanism.

```
cheatfate@DESKTOP MINGW64 /c/Projects
$  [Nimbus env]$ ./benchchronos.exe
0
10000
20000
30000
40000
50000
60000
70000
80000
90000
20s986ms402us300ns
[GC] total memory: 4886528
[GC] occupied memory: 822704
[GC] stack scans: 2273
[GC] stack cells: 59
[GC] cycle collections: 568
[GC] max threshold: 4194304
[GC] zct capacity: 1024
[GC] max cycle table size: 0
[GC] max pause time [ms]: 0
[GC] max stack size: 2288

0 pending Future[T] objects found:


cheatfate@DESKTOP MINGW64 /c/Projects
$  [Nimbus env]$ ./benchchronos.exe
0
10000
20000
30000
40000
50000
60000
70000
80000
90000
20s879ms448us600ns
[GC] total memory: 4886528
[GC] occupied memory: 822992
[GC] stack scans: 2273
[GC] stack cells: 59
[GC] cycle collections: 568
[GC] max threshold: 4194304
[GC] zct capacity: 1024
[GC] max cycle table size: 0
[GC] max pause time [ms]: 0
[GC] max stack size: 2288

0 pending Future[T] objects found:


cheatfate@DESKTOP MINGW64 /c/Projects
$  [Nimbus env]$ ./benchchronos.exe
0
10000
20000
30000
40000
50000
60000
70000
80000
90000
20s983ms319us200ns
[GC] total memory: 4886528
[GC] occupied memory: 822704
[GC] stack scans: 2273
[GC] stack cells: 59
[GC] cycle collections: 568
[GC] max threshold: 4194304
[GC] zct capacity: 1024
[GC] max cycle table size: 0
[GC] max pause time [ms]: 0
[GC] max stack size: 2288

0 pending Future[T] objects found:
```

**Comment by arnetheduck** [comment]
this test has very few in-flight futures - ie to test the overhead, one would have to have for example 100000 async tasks running in parallel - in this example, the gc is never really stressed (also because there's very little memory on the heap in general, and a very small stack

**Pull request merged**
